# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mehraan Baratian's Home page
email: mehraanbr.31@gmail.com
description: "This is a Personal Home Page of Mehraan Baratian ( Hardware Engneering at Shiraz University )<br> <a href='http://cse.shirazu.ac.ir'>CSE Department of Shiraz University </a>"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mehraanbr31.github.io" # the base hostname & protocol for your site
twitter_username: mehraanbr.31
github_username:  mehraanbr31

# Build settings
markdown: kramdown
